### ISSUE TITLE
angular2-polymer does not work with shady DOM in Angular 2.2.0

### ISSUE THREAD

**Issue by samiheikki** [platosha/angular-polymer#104]
Possible cause: https://github.com/angular/angular/commit/d708a8859ca3078a98e371b33ad560096070ad00

**Comment by merobal** [comment]
+1, looking forward for the fix!

**Comment by samiheikki** [comment]
As a temporary workaround, you can use angular2-polymer with Angular v.2.0.x or v.2.1.x.

**Comment by platosha** [comment]
### The Cause

Starting from v2.2, Angular uses direct DOM rendering in browser. `BrowserDomAdapter` is not invoked by `Renderer`.

Therefore, changing the default `BrowserDomAdapter` to `PolymerDomAdapter` trick used in `@vaadin/angular2-polymer` is not helpful anymore.

### Impact

The issue breaks setting Light DOM for Polymer elements in Shady DOM mode of Polymer v1.0.

### Workarounds

Switching Polymer to full Shadow DOM helps in general. But, as usual with ShadowDOM v0, in non-Chrome browsers this kind of a workaround requires using full ShadowDOM v0 polyfill, which is slow.

Downgrading Angular to v2.0 or v2.1 also helps as a temporary workaround.

### Solution Idea

Instead of `PolymerDomAdapter`, create `PolymerRenderer` by implementing the `Renderer` interface. The `PolymerRenderer` will call `Polymer.dom` APIs instead of DOM methods.

In order to make Angular use the `PolymerRenderer`, we need to define and export custom platforms, i.e., `platformPolymer` and `platformPolymerDynamic`.

In practice, developers will have to switch the imports in their `main.ts` files to use our custom Polymer platforms instead of the default `platformBrowser` and `platformBrowserDynamic`.

#### Benefits

- Makes Polymer usage with Angular v2.2+ nice again.
- Cleaner then the current `PolymerDomAdapter` trick.
- Opens possibilities for further optimisations. Implementing the `RootRenderer` interface, which is required to use a custom `Renderer`, also provides means to use different renderers with different components. This way we could make Polymer-dependent Angular components to use `Polymer.dom` APIs, while the rest of the Angular app is using direct DOM rendering.

#### Caveats

- Requires explicit platform change from users.
- Changing the platform from defauilt `platformBrowserDynamic` breaks Ahead-of-Time compilation in the CLI projects (`$ ng build --aot`). This is because of the CLI magic, it replaces platforms on-the-fly during build using Webpack loader processing, see https://github.com/angular/angular-cli/blob/6f9d2c1b18b81335de8ccd16e27c85efad788757/packages/webpack/src/loader.ts

### Future Perspectives

With Polymer 2, these DOM render tricks will no longer be needed. Releasing Polymer 2 and the compatible elements will likely naturally resolve this issue. However, for the following several months before it happens, this issue will remain actual.

**Comment by manolo** [comment]
Good analysis ! . Do you have any estimation for the polymer renderer implementation ?

**Comment by platosha** [comment]
It is decided to postpone implementing the solution of this until early next year. For now we will just document this limitation and the workaround, see #106.

**Comment by Chabane** [comment]
In IE11, if I use 
`assets/bower_components/webcomponentsjs/webcomponents.min.js `
instead of 
`assets/bower_components/webcomponentsjs/webcomponents-lite.min.js`
The rendering is very slow

**Comment by Splaktar** [comment]
It's really unfortunate that this is postponed to 2017 Q1. What is higher priority than not working with the latest version of Angular?

**Comment by Splaktar** [comment]
Note: `Renderer` and `RootRenderer` interfaces are both still `experimental`. 

They were able to make breaking changes to `BrowserDomAdapter` because it was a [private API](https://github.com/angular/angular/commit/d708a8859ca3078a98e371b33ad560096070ad00#commitcomment-20217389). 

Since the APIs are experimental, they will continue to make breaking changes to [Renderer](https://angular.io/docs/ts/latest/api/core/index/Renderer-class.html) and [RootRenderer](https://angular.io/docs/ts/latest/api/core/index/RootRenderer-class.html) until the API is stable (no ETA?). While this does seem to be a good approach atm, it will be setting up this project for continued breakage in the future.

Is it possible to do better with the current state of Angular? Maybe not.

**Comment by Chabane** [comment]
Any news about this issue?

We can't go more than angular 2.1.1 and angular cli 2.1.1. It's our limit with angular2-polymer.

**Comment by rimvydas-urbonas** [comment]
+1

**Comment by jaichandra** [comment]
@platosha You mentioned Polymer 2 should resolve this issue. Does it work in Polymer 2.0-preview version?

**Comment by platosha** [comment]
@jaichandra I have not tried Polymer 2.0 yet, unfortunately.

**Comment by platosha** [comment]
Meanwhile, I’m working on the `PolymerRenderer` implementation, proof-of-concept is here: https://github.com/platosha/angular-polymer-renderer

The idea seems to work. It still requires to import some private APIs, although they are not used in any way except to satisfy Angular’s `Renderer` API requirements. Still have TODO: implement styling support, ViewEncapsulation modes, add tests. Trying out and any other help is highly appreciated.

UPD: the renderer repository was renamed. See updated link above.

**Comment by Splaktar** [comment]
Excellent! I would highly recommend discussing the use of the Private APIs with the Angular core team to determine if they can provide alternate solutions or start work on exposing those APIs as at least experimental.

**Comment by platosha** [comment]
@Splaktar good idea. Filed a bug about it: https://github.com/angular/angular/issues/14001

**Comment by DzmitryShylovich** [comment]
> It still requires to import some private APIs, although they are not used in any way except to satisfy Angular’s Renderer API requirements.

you can just use `any` instead of real types

**Comment by platosha** [comment]
@DzmitryShylovich oh, that is true. Thank you!

The private imports have gone, cool. 🎉

**Comment by BorntraegerMarc** [comment]
@platosha I'll sum up the problems I've had when trying out the branch `feature/renderer` here:

1. Tested with Angular 2.1.2 (and 2.4.8) with shady DOM and `webcomponents-lite` polyfill: direct polymer properties does not seem to work. So this: `<paper-avatar mini></paper-avatar>` seems to have no effect
2. iOS (safari and chrome) seems not to render correctly. Safari on OSX works fine.
