### ISSUE TITLE
Merge npm package to this repo

### ISSUE THREAD

**Issue by BorntraegerMarc** [platosha/angular-polymer#127]
Merge the existing https://www.npmjs.com/package/angular-polymer npm package so that this repo is used to publish new versions. I'm not expert but maybe we can use something like this:
https://docs.npmjs.com/cli/unpublish

**Comment by MarkPieszak** [comment]
Yeah whoever has login & write privileges to the old vaadin package, should (instead of unpublishing it, right now at least) *deprecate* the newest version of the vaadin one, so we can start making all new updates to `angular-polymer` instead. Eventually we can unpublish the other one a year from now or something maybe?

**Comment by BorntraegerMarc** [comment]
I think the problem is more related to a recent repo rename. The angular-polymer that is published actually belongs to this repo: https://github.com/platosha/angular-polymer-renderer

And because @platosha himself published it only himself can change it again...

**Comment by MarkPieszak** [comment]
Ahh didn't know it existed already apologies! Yes then we'd want to un-publish for sure.

**Comment by platosha** [comment]
No need to unpublish it, npm registry is not bound to github.

Since I have registered and have rights over https://www.npmjs.com/package/angular-polymer, technically I can publish this package from this repo already.
