### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by nishantgirbar** [platosha/angular-polymer#30]
When i am trying to use polymer component i am getting below issue:
![polymerexception](https://cloud.githubusercontent.com/assets/18031306/16238908/0eb0eed2-3800-11e6-85cd-8319f2d3cb92.PNG)

TypeError: Cannot read property 'indexOf' of undefined
        at Object.PolymerElement (http://localhost:8080/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:70:86)

**Comment by platosha** [comment]
Hi, I believe it’s a known issue.

The reason is that the Polymer element has not been registered yet at the moment when `PolymerElement('element-name')` is called in your Angular 2 component. It is required to have your Polymer elements loaded and registered before the Angular 2 application is imported.

This is why we advise to import Polymer elements in the `<head>` section of the index.html file, before the main Angular 2 application code, and suggest to wrap the `System.import('app')` call in the `WebComponentsReady` event listener, as documented in our [Angular 2 with Polymer Elements Tutorial](https://vaadin.com/docs/-/part/elements/angular2-polymer/tutorial-index.html).

We indeed should give a more descriptive error message on that, as requested in #27
