### ISSUE TITLE
How to subscribe to Polymer paper-dropdown-menu value change event?

### ISSUE THREAD

**Issue by santiago-elustondo** [platosha/angular-polymer#36]
Hey guys, I know this isn't really your area of concern, but I thought maybe you'd have some opinion/experience to share. It might help those who are trying to get going with angular2-polymer.

The [paper-input](https://elements.polymer-project.org/elements/paper-input) component has a "changed" event that you can use to implement 2-way binding. I'm looking for an equivalent for [paper-dropdown-menu](https://elements.polymer-project.org/elements/paper-dropdown-menu). The paper-dropdown-menu api provides the "value" property as a getter, but not as an event.

[paper-listbox](https://elements.polymer-project.org/elements/paper-listbox) has an event like the one described ("iron-select"), but the event data does not tell you which paper-dropdown-menu it is a child of.

So far the best way I've been able to accomplish data binding is by listening to all paper-listbox "iron-select" events, and then grabbing the values of all dropdowns every time.

In Angular2:

```
/* template */

<paper-dropdown-menu #dropdown1 label="Your favourite pastry">
  <paper-listbox (iron-select)="onSelectDropdown($event)" class="dropdown-content">
    <paper-item>Croissant</paper-item>
    <paper-item>Donut</paper-item>
    <paper-item>Financier</paper-item>
    <paper-item>Madeleine</paper-item>
  </paper-listbox>
</paper-dropdown-menu>

//and another 2...

/* class */

@ViewChild('dropdown1') dropdown1:any;
@ViewChild('dropdown2') dropdown2:any;
@ViewChild('dropdown3') dropdown3:any;

onSelectDropdown(event:any){
  setTimeout(()=>{
    this.data = {
     thing1: this.dropdown1.nativeElement.value;
     thing2: this.dropdown2.nativeElement.value;
     thing3: this.dropdown3.nativeElement.value;
    }
  }, 0);
}
```

This does not seem like a very elegant way to do it, especially since I have to wrap the getter ("value") calls in a timeout. This is because the event fires before it propagates to the parent (paper-dropdown-menu).

Any thoughts on this?

**Comment by platosha** [comment]
`paper-dropdown-menu` has these properties: `value`, `selectedItem`, and `selectedItemLabel`. All of them have `notify: true` flag, so they should notify parents for their value change. This is stated in the element’s API documentation, the properties have the “notifies” mark there.

The “notify” flag means, that whenever the property value changes, the element fires a `property-name-changed` event with the new data. Detailed information about the [change notification protocol](https://www.polymer-project.org/1.0/docs/devguide/data-binding#change-notification-protocol) is in the Polymer docs.

We also support the Polymer’s change notification protocol in angular2-polymer, so the Angular 2 two-way bindings should be triggered after Polymer’s change events. Normally, you should be able to just bind the `value` property with two-way data binding in your Angular 2 component. If it doesn’t work, I guess that is because of the `value` of `paper-dropdown-menu` doesn’t update, probably due to the same issue as in #34.

**Comment by santiago-elustondo** [comment]
Very helpful, thanks
