### ISSUE TITLE
No value accessor for form control

### ISSUE THREAD

**Issue by cschroeter** [platosha/angular-polymer#76]
There is no value accessor for paper-input elements using reactiveformmodules

``` html
<form [formGroup]="form">
  <paper-input label="Name" formControlName="name"></paper-input>
</form>
```

``` typescript
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [PolymerElement('paper-input')]
})
export class AppComponent {

  public form: FormGroup;

  constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      name: ['']
    });
  }
}
```

```
browser_adapter.js:84ORIGINAL EXCEPTION: No value accessor for form control with name: 'name'
```

**Comment by Chabane** [comment]
Add ngControlDefault on paper-item.

**Comment by cschroeter** [comment]
Like this?

``` typescript
<paper-input label="Name" formControlName="name" ngControlDefault></paper-input>
```

Unfortunately still no control value accessor :(

**Comment by Chabane** [comment]
See this link for more informations : 
[angular2 rc.5 custom input, No value accessor for form control with unspecified name](http://stackoverflow.com/questions/38958347/angular2-rc-5-custom-input-no-value-accessor-for-form-control-with-unspecified)
This error is occurred only with externals components like material 2 & polymer.

**Comment by platosha** [comment]
@cschroeter could you please run `$ npm ls` and give the output here?

The issue could be caused by having two different Angular revisions in your project dependencies. There might be two different instances of the `@angular/forms` package installed, one for the project (under the `node_modules/@angular/forms` path), and another one for the `@vaadin/angular2-polymer` package specifically (under `node_modules/@vaadin/angular2-polymer/node_modules/@angular/forms`).

Under the hood, the `PolymerElement` function output should provide the value accessor for the paper-input element. Therefore, normally it should work without the `ngControlDefault` attribute. But in case if you have different instances of the forms module, the value accessor it provides for the local forms module has no effect for the forms module that is used in the project.

If this is the case, please try to adjust your project dependencies. The Angular versions, that your project and the `@vaadin/angular2-polymer` package depend on, should match, so that when you run `$ npm install`, it flattens the dependencies and results in a single Angular 2 modules installation for your project.

**Comment by cschroeter** [comment]
You should use peerDependencies to express your dependencies to `@angular/form`. You can find more information about peerDependencies  [here](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies).

But anyway I using 0.3.0 like you have defined in your package.json

**Comment by platosha** [comment]
@cschroeter good point, thanks 👍 

Please double-ensure that there are no local Angular modules.

While verifying the issue, i’ve reproduced the error you have at first. But then noticed myself that I have two installations of Angular 2 modules in the project. Adjusting the dependencies resolved the error for me.

**Comment by cschroeter** [comment]
I've run `npm ls` and there was no sub dependency listet for @vaadin/angular2-polymer.

```
...
├── @angular/forms@0.3.0
├── @angular/http@2.0.0-rc.5
├── @angular/platform-browser@2.0.0-rc.5
├── @angular/platform-browser-dynamic@2.0.0-rc.5
├── @angular/router@3.0.0-rc.1
├── @types/jasmine@2.2.32
├─┬ @types/protractor@1.5.17
│ └── @types/selenium-webdriver@2.44.27
├── @vaadin/angular2-polymer@1.0.0-beta3
├─┬ angular-cli@1.0.0-beta.11-webpack.2

```

**Comment by platosha** [comment]
Could also be a module loader or build issue. For example, if `@angular/forms` and `@vaadin/angualr2-polymer` are compiled into separate JS files, there might be two instances of the forms module in those files.

Are you using System.js or webpack? Can you share the isolated reproduction?

**Comment by cschroeter** [comment]
@platosha with the latest rc6 / beta4 it works 👍
