### ISSUE TITLE
E2E tests timeout in angular-cli projects

### ISSUE THREAD

**Issue by components-stalker** [platosha/angular-polymer#90]

**Comment by platosha** [comment]
The reason is the incompatibilities between Zone.js and Polymer.

`Polymer.Async`, used by Polymer’s debouncers, treats the `setTimeout` return value as a number, and sometimes calls `clearTimeout` with the `setTimeout`’s return value converted to a number. At the same time, when using Zone.js, the patched `setTimeout`/`clearTimeout` timer methods work with `Task` instances rather then with numbers. So when a Polymer debouncer clears a timeout, the corresponding Zone task is not cancelled and remain counted as “scheduled” in Angular. This makes the protractor tests to timeout waiting for the sync.

Polymer’s behaviour seems spec-compliant. Seems that this has to be fixed in Zone. See: https://github.com/angular/zone.js/issues/461

**Comment by platosha** [comment]
The timeouts clearing issue was fixed in Zone.js.

E2E tests are now working with master Zone.js.
